spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_endecrypt
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.spike.model